
this.server.url=http://localhost:8080

ecommerce.security.key=X-API-KEY
ecommerce.security.value=

jwt.access.secret=Y29tcGxleC1zZWNyZXQta2V5LWZvci1hY2Nlc3MtdG9rZW4tZW5jcnlwdGlvbi1wbGVhc2UtY2hhbmdlLWluLXByb2R1Y3Rpb24
jwt.refresh.secret=Y29tcGxleC1zZWNyZXQta2V5LWZvci1yZWZyZXNoLXRva2VuLWVuY3J5cHRpb24tcGxlYXNlLWNoYW5nZS1pbi1wcm9kdWN0aW9u
jwt.access.expiration=3600000
jwt.refresh.expiration=604800000

ecommerce.server.allowed.host.name=localhost:8080
ecommerce.server.allowed.origin.name=http://localhost:8080