
this.server.url=http://localhost:8080

ecommerce.security.key=X-API-KEY
ecommerce.security.value=

jwt.access.secret=
jwt.refresh.secret=
jwt.access.expiration=3600000
jwt.refresh.expiration=604800000

ecommerce.server.allowed.host.name=
ecommerce.server.allowed.origin.name=